//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetStarterKit.Models.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public long SubscriptionId { get; set; }
        public Nullable<int> SubscriptionType { get; set; }
        public Nullable<int> MaximumBooksAllowed { get; set; }
        public Nullable<System.DateTime> SubscribedDate { get; set; }
        public Nullable<System.DateTime> SubscriptionExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
