//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetStarterKit.Models.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionType
    {
        public int SubsciptionTypeID { get; set; }
        public string SubscriptionType1 { get; set; }
    }
}
