//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetStarterKit.Models.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> Mobile { get; set; }
        public int Main { get; set; }
        public int Cross { get; set; }
        public long SubscriptionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
